server:
  port: 9000

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url.defaultZone: http://localhost:9100/eureka/

spring:
  application:
    name: cherry-config-center-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aa9288s/cherry-cloud.git
          username: aa9288s
          password: aa318999745
          default-label: master
          search-paths: config