server:
  port: 9200

spring:
  application:
    name: gateway

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
    register-with-eureka: false

zuul:
  routes:
    app:
      path: /app/**
      service-id: cherry-app

