server:
  port: 9100

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    status-page-url: /info
    health-check-url-path: /health
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

